const data = [
  {
    id: 10,
    title: 'projects.bookManager.title',
    description: 'projects.bookManager.description',
    linkRep: 'https://github.com/Daniela-Alves2004/gerenciador-livros',
    textgithub: 'projects.common.github',
  },
  {
    id: 3,
    title: 'projects.attendanceSystem.title',
    description: 'projects.attendanceSystem.description',
    linkRep: 'https://github.com/Daniela-Alves2004/registro-presenca-oficina',
    textgithub: 'projects.common.github',
  },
  {
    id: 1,
    title: 'projects.srDente.title',
    description: 'projects.srDente.description',
    urlSite: 'https://sr-dente.vercel.app',
    linkRep: 'https://github.com/luscabap/sr-dente.git',
    textgithub: 'projects.common.github',
    textSite: 'projects.common.accessWebsite',
  },
  {
    id: 2,
    title: 'projects.digitalGirls.title',
    description: 'projects.digitalGirls.description',
    urlSite: 'https://daniela-alves2004.github.io/projeto-web-front-end/',
    linkRep: 'https://github.com/Daniela-Alves2004/projeto-web-front-end.git',
    textgithub: 'projects.common.github',
    textSite: 'projects.common.accessWebsite',
  },
  {
    id: 4,
    title: 'projects.squadRoxo.title',
    description: 'projects.squadRoxo.description',
    urlSite: 'https://pipoca-agil-apresentacao.vercel.app',
    linkRep: 'https://github.com/luscabap/pipoca-agil-apresentacao',
    textgithub: 'projects.common.github',
    textSite: 'projects.common.accessWebsite',
  },
  {
    id: 5,
    title: 'projects.marioGame.title',
    description: 'projects.marioGame.description',
    urlSite: 'https://daniela-alves2004.github.io/Jogo-Mario/',
    linkRep: 'https://github.com/Daniela-Alves2004/Jogo-Mario',
    textgithub: 'projects.common.github',
    textSite: 'projects.common.accessWebsite',
  },
  {
    id: 6,
    title: 'projects.todoList.title',
    description: 'projects.todoList.description',
    urlSite: 'https://daniela-alves2004.github.io/lista-de-tarefas/',
    linkRep: 'https://github.com/Daniela-Alves2004/lista-de-tarefas',
    textgithub: 'projects.common.github',
    textSite: 'projects.common.accessWebsite',
  },
  {
    id: 9,
    title: 'projects.ticketSystem.title',
    description: 'projects.ticketSystem.description',
    linkRep: 'https://github.com/Daniela-Alves2004/sistema-venda-ingresso',
    textgithub: 'projects.common.github',
  },
  {
    id: 7,
    title: 'projects.restApi.title',
    description: 'projects.restApi.description',
    linkRep: 'https://github.com/Daniela-Alves2004/registro-presenca-oficina',
    textgithub: 'projects.common.github',
  },
  {
    id: 8,
    title: 'projects.backendApi.title',
    description: 'projects.backendApi.description',
    linkRep: 'https://github.com/Daniela-Alves2004/registro-presenca-oficina',
    textgithub: 'projects.common.github',
  },
];

export default data;
